version: '3.8'

services:
  azure-openai-bot:
    build: .
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
    restart: unless-stopped
    container_name: azure-openai-bot
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"